
language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_script:
  - sudo apt-get install apt-transport-https
  - sudo wget https://www.arangodb.com/repositories/arangodb2/Debian_7.0/Release.key
  - sudo apt-key add - < Release.key
  - sudo echo 'deb https://www.arangodb.com/repositories/arangodb2/Debian_7.0/ /' | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -q
  - sudo apt-get install arangodb=2.4.1
  - sudo service arangodb stop

script:
  - ./gradlew intTest
